# Generated by Django 4.2.3 on 2023-07-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=50)),
                ('currency_code', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
    ]
