# Generated by Django 4.2.3 on 2023-07-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_telegramuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='chat_id',
            field=models.IntegerField(default=0),
        ),
    ]
