# Generated by Django 4.2.3 on 2023-08-08 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_telegramuser_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_cur_choice', to='bot.currency')),
                ('second_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_cur_choice', to='bot.currency')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_choice', to='bot.telegramuser')),
            ],
            options={
                'verbose_name': 'User watchlist',
                'verbose_name_plural': 'User watchlists',
                'db_table': 'user_watchlist',
            },
        ),
    ]
