# Generated by Django 4.2.3 on 2023-08-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_userwatchlist_exchange_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwatchlist',
            old_name='user_id',
            new_name='user',
        ),
    ]
